In [1]:
import pandas as pd
df = pd.read_csv(r'file1.csv')
df.tail()

,Unnamed: 0,name,latitude,longitude,addr:street,addr:city,addr:province
1488732,1488732,Sunrise Academy Capmus.1,24.918331,67.138338,Sunrise Academy Road,Karachi,Sindh
1488733,1488733,Sunrise Academy,24.918219,67.138864,Sunrise Academy Road,Karachi,Sindh
1488734,1488734,Old Racecourse Ground,67.041950,67.041950,Race Course Road,Karachi,Sindh
1488735,1488735,Pakistan railway hassan hospital,67.042522,67.042522,Mc Niel Road,Karachi,Sindh
1488736,1488736,Ks Corporation,67.117868,67.117868,Shah Muhammad Road,Karachi,Sindh